### ISSUE TITLE
Windows CI failures Late June 2025

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1872]
A few CI jobs on Windows started to fail, probably due to the update to the latest VS on the github action machines (that unfortunatly we can't control/pin) and/or the update of vs2022 in conda-forge (see https://github.com/conda-forge/compilers-feedstock/pull/72 and https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7473).

**Comment by traversaro** [comment]
Let's start with the Pixi CI failure. The pixi CI locks everything (in the scheduled builds), so the regression is for sure due to the environment.

Last successful: https://github.com/robotology/robotology-superbuild/actions/runs/15696659700
First failing: https://github.com/robotology/robotology-superbuild/actions/runs/15769910150/job/44452871708

**Comment by traversaro** [comment]
The failure is:

~~~
2025-06-20T03:27:40.1499679Z [326/416] Performing configure step for 'ergocub-software'
2025-06-20T03:27:40.1501271Z FAILED: [code=1] src/ergocub-software/CMakeFiles/YCMStamp/ergocub-software-configure D:/a/robotology-superbuild/robotology-superbuild/.build/src/ergocub-software/CMakeFiles/YCMStamp/ergocub-software-configure 
2025-06-20T03:27:40.1505959Z C:\Windows\system32\cmd.exe /C "cd /D D:\a\robotology-superbuild\robotology-superbuild\.build\src\ergocub-software && D:\a\robotology-superbuild\robotology-superbuild\.pixi\envs\default\Library\bin\cmake.exe --no-warn-unused-cli -DCMAKE_PREFIX_PATH:PATH=D:/a/robotology-superbuild/robotology-superbuild/.build/install;D:/a/robotology-superbuild/robotology-superbuild/.pixi/envs/default/Library -DCOMPILE_ergoCubEmotions:BOOL=ON -GNinja -CD:/a/robotology-superbuild/robotology-superbuild/.build/src/ergocub-software/CMakeFiles/YCMTmp/ergocub-software-cache-Release.cmake -S D:/a/robotology-superbuild/robotology-superbuild/src/ergocub-software -B D:/a/robotology-superbuild/robotology-superbuild/.build/src/ergocub-software && D:\a\robotology-superbuild\robotology-superbuild\.pixi\envs\default\Library\bin\cmake.exe -E touch D:/a/robotology-superbuild/robotology-superbuild/.build/src/ergocub-software/CMakeFiles/YCMStamp/ergocub-software-configure"
2025-06-20T03:27:40.1509675Z Not searching for unused variables given on the command line.
2025-06-20T03:27:40.1511020Z loading initial cache file D:/a/robotology-superbuild/robotology-superbuild/.build/src/ergocub-software/CMakeFiles/YCMTmp/ergocub-software-cache-Release.cmake
2025-06-20T03:27:40.1512228Z -- The C compiler identification is MSVC 19.29.30158.0
2025-06-20T03:27:40.1512684Z -- The CXX compiler identification is MSVC 19.29.30158.0
2025-06-20T03:27:40.1513099Z -- Detecting C compiler ABI info
2025-06-20T03:27:40.1513419Z -- Detecting C compiler ABI info - done
2025-06-20T03:27:40.1514299Z -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe - skipped
2025-06-20T03:27:40.1515234Z -- Detecting C compile features
2025-06-20T03:27:40.1515605Z -- Detecting C compile features - done
2025-06-20T03:27:40.1515991Z -- Detecting CXX compiler ABI info
2025-06-20T03:27:40.1516363Z -- Detecting CXX compiler ABI info - done
2025-06-20T03:27:40.1517568Z -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe - skipped
2025-06-20T03:27:40.1518554Z -- Detecting CXX compile features
2025-06-20T03:27:40.1518832Z -- Detecting CXX compile features - done
2025-06-20T03:27:40.1519317Z -- Found YCM: D:/a/robotology-superbuild/robotology-superbuild/.build/install/share/cmake/YCM (found version "0.18.3")
2025-06-20T03:27:40.1520111Z -- Found YARP: D:/a/robotology-superbuild/robotology-superbuild/.build/install/lib/cmake/YARP (found version "3.12.0+1-20250604.6+git285f6317e")
2025-06-20T03:27:40.1520896Z -- Found YCM: D:/a/robotology-superbuild/robotology-superbuild/.build/install/share/cmake/YCM (found version "0.18.3")
2025-06-20T03:27:40.1521358Z -- OpenCV ARCH: x64
2025-06-20T03:27:40.1521533Z -- OpenCV RUNTIME: vc14
2025-06-20T03:27:40.1521710Z -- OpenCV STATIC: OFF
2025-06-20T03:27:40.1522214Z CMake Warning at D:/a/robotology-superbuild/robotology-superbuild/.pixi/envs/default/Library/cmake/OpenCVConfig.cmake:190 (message):
2025-06-20T03:27:40.1522845Z   Found OpenCV Windows Pack but it has no binaries compatible with your
2025-06-20T03:27:40.1523161Z   configuration.
2025-06-20T03:27:40.1523267Z 
2025-06-20T03:27:40.1523442Z   You should manually point CMake variable OpenCV_DIR to your build of OpenCV
2025-06-20T03:27:40.1523761Z   library.
2025-06-20T03:27:40.1523927Z Call Stack (most recent call first):
2025-06-20T03:27:40.1524219Z   src/modules/ergoCubEmotions/CMakeLists.txt:10 (find_package)
2025-06-20T03:27:40.1524469Z 
2025-06-20T03:27:40.1524473Z 
2025-06-20T03:27:40.1524649Z CMake Error at src/modules/ergoCubEmotions/CMakeLists.txt:10 (find_package):
2025-06-20T03:27:40.1524988Z   Found package configuration file:
2025-06-20T03:27:40.1525144Z 
2025-06-20T03:27:40.1525425Z     D:/a/robotology-superbuild/robotology-superbuild/.pixi/envs/default/Library/cmake/OpenCVConfig.cmake
2025-06-20T03:27:40.1525792Z 
2025-06-20T03:27:40.1525959Z   but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
2025-06-20T03:27:40.1526619Z   NOT FOUND.
2025-06-20T03:27:40.1526970Z 
~~~

However, the failure seems that somehow the CI is not using the lock file, perhaps we should be using `--locked`.

**Comment by traversaro** [comment]
> The pixi CI locks everything (in the scheduled builds), so the regression is for sure due to the environment.

No sorry, I forgot that in scheduled builds the lockfile is not used. So, the problem is that the new opencv version that requires vs2022 was used, but cxx-compiler still uses vs2019, this will be solved by https://github.com/conda-forge/compilers-feedstock/pull/72 .

For what regard conda builds, the error is:

~~~
2025-06-21T03:57:44.6128790Z     qpsolvers-eigen-osqp.vcxproj -> D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\bin\Release\qpsolvers-eigen-osqp.dll
2025-06-21T03:57:44.6777310Z     Building Custom Rule D:/a/robotology-superbuild/robotology-superbuild/src/QpSolversEigen/plugins/proxqp/CMakeLists.txt
2025-06-21T03:57:44.7397014Z     QpSolversEigenProxqp.cpp
2025-06-21T03:57:50.8193099Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: Internal compiler error. [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8198409Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\lower-trees.cpp', line 6555) [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8202643Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: To work around this problem, try simplifying or changing the program near the locations listed above. [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8207002Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: If possible please provide a repro here: https://developercommunity.visualstudio.com  [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8211191Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: Please choose the Technical Support command on the Visual C++  [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8215194Z D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54): error C1001: Help menu, or open the Technical Support help file for more information [D:\a\robotology-superbuild\robotology-superbuild\b\src\QpSolversEigen\plugins\proxqp\qpsolvers-eigen-proxqp.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\QpSolversEigen.vcxproj]
2025-06-21T03:57:50.8220137Z     (compiling source file '../../../../../src/QpSolversEigen/plugins/proxqp/QpSolversEigenProxqp.cpp')
2025-06-21T03:57:50.8224000Z         D:\a\robotology-superbuild\robotology-superbuild\b\install\include\proxsuite\linalg\veg\tuple.hpp(345,54):
~~~

This seems indeed some kind of internal compiler error in proxqp/qpsolvers-eigen.

**Comment by traversaro** [comment]
> After [#1875](https://github.com/robotology/robotology-superbuild/pull/1875), all Windows jobs fail in the same way. As we did not see these failures on qpsolvers-eigen CI and feedstock CI, I wonder if the problem is the proxqp version.

Indeed it seems that in the superbuild with have 0.7.1, while in conda-forge we have 0.7.2 . Hopefully 0.7.2 will fix this, I guess this was somehow related to one of the changes listed in https://github.com/Simple-Robotics/proxsuite/releases/tag/v0.7.2 .
