### ISSUE TITLE
conda-forge CI failure End of November 2023 due to graphviz update

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#1537]
Failure on Windows, macOS, Linux:

~~~
2023-11-24T02:16:57.2275069Z [17/1232] Building CXX object extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/private/QGVCore.cpp.o
2023-11-24T02:16:57.2276505Z FAILED: extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/private/QGVCore.cpp.o 
2023-11-24T02:16:57.2293131Z /usr/share/miniconda3/envs/test/bin/x86_64-conda-linux-gnu-c++ -DBUILDING_YARP -DQGVCORE_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv/YARP_priv_qgvcore_autogen/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv -I/usr/share/miniconda3/envs/test/include/graphviz -isystem /usr/share/miniconda3/envs/test/include/qt -isystem /usr/share/miniconda3/envs/test/include/qt/QtWidgets -isystem /usr/share/miniconda3/envs/test/include/qt/QtGui -isystem /usr/share/miniconda3/envs/test/include/qt/QtCore -isystem /usr/share/miniconda3/envs/test/./mkspecs/linux-g++ -w -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda3/envs/test/include -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MT extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/private/QGVCore.cpp.o -MF extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/private/QGVCore.cpp.o.d -o extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/private/QGVCore.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.cpp
2023-11-24T02:16:57.2309124Z In file included from /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.cpp:18:
2023-11-24T02:16:57.2312506Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h: In static member function 'static Agraph_t* QGVCore::agmemread2(const char*)':
2023-11-24T02:16:57.2600802Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:14: error: 'Agdisc_t' {aka 'struct Agdisc_s'} has no member named 'mem'
2023-11-24T02:16:57.2602825Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.2603348Z       |              ^~~
2023-11-24T02:16:57.2605890Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:21: error: 'AgMemDisc' was not declared in this scope; did you mean 'AgIoDisc'?
2023-11-24T02:16:57.2607891Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.2608461Z       |                     ^~~~~~~~~
2023-11-24T02:16:57.2608994Z       |                     AgIoDisc
2023-11-24T02:16:57.2610047Z [18/1232] Building CXX object extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVEdge.cpp.o
2023-11-24T02:16:57.2611405Z FAILED: extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVEdge.cpp.o 
2023-11-24T02:16:57.2626446Z /usr/share/miniconda3/envs/test/bin/x86_64-conda-linux-gnu-c++ -DBUILDING_YARP -DQGVCORE_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv/YARP_priv_qgvcore_autogen/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv -I/usr/share/miniconda3/envs/test/include/graphviz -isystem /usr/share/miniconda3/envs/test/include/qt -isystem /usr/share/miniconda3/envs/test/include/qt/QtWidgets -isystem /usr/share/miniconda3/envs/test/include/qt/QtGui -isystem /usr/share/miniconda3/envs/test/include/qt/QtCore -isystem /usr/share/miniconda3/envs/test/./mkspecs/linux-g++ -w -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda3/envs/test/include -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MT extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVEdge.cpp.o -MF extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVEdge.cpp.o.d -o extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVEdge.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/QGVEdge.cpp
2023-11-24T02:16:57.2710315Z In file included from /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/QGVEdge.cpp:19:
2023-11-24T02:16:57.2713394Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h: In static member function 'static Agraph_t* QGVCore::agmemread2(const char*)':
2023-11-24T02:16:57.2716950Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:14: error: 'Agdisc_t' {aka 'struct Agdisc_s'} has no member named 'mem'
2023-11-24T02:16:57.3122074Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.3123152Z       |              ^~~
2023-11-24T02:16:57.3125440Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:21: error: 'AgMemDisc' was not declared in this scope; did you mean 'AgIoDisc'?
2023-11-24T02:16:57.3127301Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.3127860Z       |                     ^~~~~~~~~
2023-11-24T02:16:57.3128374Z       |                     AgIoDisc
2023-11-24T02:16:57.3129423Z [19/1232] Building CXX object extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVNode.cpp.o
2023-11-24T02:16:57.3130823Z FAILED: extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVNode.cpp.o 
2023-11-24T02:16:57.3146265Z /usr/share/miniconda3/envs/test/bin/x86_64-conda-linux-gnu-c++ -DBUILDING_YARP -DQGVCORE_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv/YARP_priv_qgvcore_autogen/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/YARP/extern/qgv -I/usr/share/miniconda3/envs/test/include/graphviz -isystem /usr/share/miniconda3/envs/test/include/qt -isystem /usr/share/miniconda3/envs/test/include/qt/QtWidgets -isystem /usr/share/miniconda3/envs/test/include/qt/QtGui -isystem /usr/share/miniconda3/envs/test/include/qt/QtCore -isystem /usr/share/miniconda3/envs/test/./mkspecs/linux-g++ -w -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda3/envs/test/include -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MT extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVNode.cpp.o -MF extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVNode.cpp.o.d -o extern/qgv/CMakeFiles/YARP_priv_qgvcore.dir/qgv/QGVCore/QGVNode.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/QGVNode.cpp
2023-11-24T02:16:57.3161385Z In file included from /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/QGVNode.cpp:19:
2023-11-24T02:16:57.3164582Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h: In static member function 'static Agraph_t* QGVCore::agmemread2(const char*)':
2023-11-24T02:16:57.3168104Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:14: error: 'Agdisc_t' {aka 'struct Agdisc_s'} has no member named 'mem'
2023-11-24T02:16:57.3169969Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.3170476Z       |              ^~~
2023-11-24T02:16:57.3172427Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/YARP/extern/qgv/qgv/QGVCore/private/QGVCore.h:96:21: error: 'AgMemDisc' was not declared in this scope; did you mean 'AgIoDisc'?
2023-11-24T02:16:57.3174412Z    96 |         disc.mem = &AgMemDisc;
2023-11-24T02:16:57.3174936Z       |                     ^~~~~~~~~
2023-11-24T02:16:57.3175443Z       |                     AgIoDisc
~~~

The problem is the installed graphviz went from 8 to 9. We can fix this, but probably the quickest fix (considering also that we would need the fix to reach a released version) is to pin graphviz version.

**Comment by traversaro** [comment]
A similar failure is present in https://github.com/conda-forge/qgv-feedstock/pull/2 .

**Comment by traversaro** [comment]
Related change from the changelog (https://gitlab.com/graphviz/graphviz/-/blob/main/CHANGELOG.md#900-2023-09-11):

> Breaking: The concept of “memory allocator discipline” has been removed,
along with the type Agmemdisc_t and fields Agdisc_t.mem and
Agdstate_t.mem.

**Comment by traversaro** [comment]
A fix for this was done in gazebo-classic in https://github.com/gazebosim/gazebo-classic/pull/3345 .

**Comment by traversaro** [comment]
This should be fixed once the following PRs are merged and released:

* https://github.com/robotology/ycm/pull/438
* https://github.com/robotology/ycm/pull/439
* https://github.com/robotology/yarp/pull/3056

**Comment by traversaro** [comment]
Closing the issue as we added a workaround of pinning graphviz to 8.
