### PR TITLE
Add ROBOTOLOGY_USES_MUJOCO option that builds mujoco C/C++ library and mujoco-simulink-blockset

### PR DESCRIPTION
**Pull request by traversaro**
First attempt to MuJoCo integration in the superbuild:
* At the moment, I just build the C++ part of MuJoCo, as the main goal here is to simplify the installation of the simulink bindings of MuJoCo, while the Python bindings of MuJoCo are quite easy to install via PyPI or conda-forge
* Differently from other `ROBOTOLOGY_USES_***` options, in this case MuJoCo is built by the superbuild, as unfortunatly there is no apt binary for MuJoCo
* MuJoCo is built from a fork at the moment, but the changes that we need have been upstreamed in https://github.com/deepmind/mujoco/pull/937
* Similarly to what we do for osqp ( https://github.com/ami-iit/osqp-matlab-cmake-buildsystem ) and casadi ( https://github.com/ami-iit/casadi-matlab-bindings ), we prepare a simple drop-in replacement build system to build `mujoco-simulink-blockset` via CMake and for using system-provided dependencies instead of the one vendored: https://github.com/ami-iit/mujoco-simulink-blockset-cmake-buildsystem
* For what regards installation with apt dependencies, the new option `ROBOTOLOGY_USES_MUJOCO` will only be compatible with Ubuntu 22.04 . If you have an older Ubuntu and you want to test it, feel free to use conda-forge dependencies.

If you want to test the PR with the MATLAB/Simulink integration of MuJoCo (i.e. mujoco-simulink-blockset), you can just download this branch, enable `ROBOTOLOGY_USES_MUJOCO`  and `ROBOTOLOGY_USES_MATLAB`, compile, run the `setup.**` script, open MATLAB and then run `mj_gettingStarted` . A simulation like the following (with integrated visualization) should open:

mujoco_simulink

### CODE REVIEW

**Comment by traversaro** [comment]
Recap:
* Some Ubuntu 20.04 CI jobs are still failing due to the lack of `ccd-config.cmake`, we need to disable mujoco there
* macOS is failing and should be fixed by https://github.com/ami-iit/mujoco-simulink-blockset-cmake-buildsystem/pull/2
* Windows is failing with https://github.com/deepmind/mujoco/issues/862, if we move the integration branch to be based on 2.3.6 this problem should be solved.
* Ubuntu on Conda is failing for some Werror-related problems, we need to remove Werror on our integration branch

**Comment by traversaro** [comment]
Even by swiching to MuJoCo 2.3.6, we have the same problem of https://github.com/deepmind/mujoco/issues/862 : 

~~~
2023-06-21T14:02:12.5669002Z     glad.c
2023-06-21T14:02:12.8992033Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(487,17): error C2059: syntax error: '/' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.8996020Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(502,17): error C2059: syntax error: '/' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.8997828Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(530,17): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9000631Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(531,13): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9002476Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(533,9): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9005184Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(534,5): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9009286Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(665,16): error C2079: 'varDefaultValue' uses undefined struct 'tagVARIANT' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9014649Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(950,16): error C2079: 'varValue' uses undefined struct 'tagVARIANT' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9144292Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(319,24): error C2059: syntax error: '/' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9167584Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(378,37): error C2371: 'pvarVal': redefinition; different basic types [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9168932Z   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(510): message : see declaration of 'pvarVal' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj]
2023-06-21T14:02:12.9169984Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(379,9): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9171116Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(380,5): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9172185Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(383,3): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:12.9173661Z C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(384,1): error C2059: syntax error: '}' [D:\a\robotology-superbuild\robotology-superbuild\build\src\mujoco\mujoco.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\mujoco.vcxproj]
2023-06-21T14:02:13.0115123Z     render_context.c
2023-06-21T14:02:13.2826779Z     render_gl2.c
2023-06-21T14:02:13.3857413Z     render_gl3.c
2023-06-21T14:02:13.4896439Z     render_util.c
2023-06-21T14:02:13.5641118Z     ui_main.c
2023-06-21T14:02:13.6706705Z     Generating Code...
~~~

**Comment by traversaro** [comment]
> Even by swiching to MuJoCo 2.3.6, we have the same problem of [deepmind/mujoco#862](https://github.com/deepmind/mujoco/issues/862) :

I proposed a solution in https://github.com/deepmind/mujoco/pull/946 and I backported it to the ami-iit/integration236 branch.

**Comment by traversaro** [comment]
> > Even by swiching to MuJoCo 2.3.6, we have the same problem of [deepmind/mujoco#862](https://github.com/deepmind/mujoco/issues/862) :
> 
> I proposed a solution in [deepmind/mujoco#946](https://github.com/deepmind/mujoco/pull/946) and I backported it to the ami-iit/integration236 branch.

That does not work. I just disable that option on the Visual Studio 2019 job.
